version: '3.8'

services:
  app:
    build: .
    container_name: max_path_sum
    volumes:
      - .:/home/umair/app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=testdb

  db:
    image: postgres:13
    container_name: max_path_sum_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
